/**
 * @description Metadata types
 */
export enum SalesforceMetadataTypes {
    ANY_FIELD = 'Field',
    APEX_CLASS = 'ApexClass',
    APEX_TRIGGER = 'ApexTrigger',
    AURA_WEB_COMPONENT = 'AuraDefinitionBundle',
    COLLABORATION_GROUP = 'CollaborationGroup',
    CUSTOM_BIG_OBJECT = 'CustomBigObject',
    CUSTOM_EVENT = 'CustomEvent',
    CUSTOM_FIELD = 'CustomField',
    CUSTOM_LABEL = 'CustomLabel',
    CUSTOM_METADATA_TYPE = 'CustomMetadataType',
    CUSTOM_OBJECT = 'CustomObject',
    CUSTOM_SETTING = 'CustomSetting',
    CUSTOM_SITE = 'CustomSite',
    CUSTOM_TAB = 'CustomTab',
    DASHBOARD = 'Dashboard',
    DOCUMENT = 'Document',
    EXTERNAL_OBJECT = 'ExternalObject',
    EMAIL_TEMPLATE = 'EmailTemplate',
    FIELD_SET = 'FieldSet',
    FLOW_DEFINITION = 'FlowDefinition',
    FLOW_VERSION = 'Flow',
    HOME_PAGE_COMPONENT = 'HomePageComponent',
    KNOWLEDGE_ARTICLE = 'KnowledgeArticle',
    KNOWLEDGE_ARTICLE_VERSION = 'KnowledgeArticleVersion',
    LIGHTNING_PAGE = 'FlexiPage',
    LIGHTNING_WEB_COMPONENT = 'LightningComponentBundle',
    PAGE_LAYOUT = 'Layout',
    PERMISSION_SET = 'PermissionSet',
    PERMISSION_SET_GROUP = 'PermissionSetGroup',
    PERMISSION_SET_LICENSE = 'PermissionSetLicense',
    PROFILE = 'Profile',
    PUBLIC_GROUP = 'PublicGroup',
    QUEUE = 'Queue',
    RECORD_TYPE = 'RecordType',
    REPORT = 'Report',
    ROLE = 'UserRole',
    TECHNICAL_GROUP = 'TechnicalGroup',
    STANDARD_FIELD = 'StandardField',
    STANDARD_OBJECT = 'StandardEntity',
    STATIC_RESOURCE = 'StaticResource',
    USER = 'User',
    VALIDATION_RULE = 'ValidationRule',
    VISUAL_FORCE_COMPONENT = 'ApexComponent',
    VISUAL_FORCE_PAGE = 'ApexPage',
    WEB_LINK = 'WebLink',
    WORKFLOW_RULE = 'WorkflowRule',
}