/**
 * @description Data aliases
 */
export enum DataAliases {
    SFDC_ApexTestMethodResult = 'Apex Test Method', 
    SFDC_ApexClass = 'Apex Class', 
    SFDC_ApexTrigger = 'Apex Trigger', 
    SFDC_Application = 'Application', 
    SFDC_AppPermission = 'App Permission', 
    SFDC_Browser = 'Browser', 
    SFDC_CollaborationGroup = 'Chatter Group', 
    SFDC_CustomLabel = 'Custom Label', 
    SFDC_CustomTab = 'Custom Tab', 
    SFDC_Dashboard = 'Dashboard', 
    SFDC_Document = 'Document', 
    SFDC_EmailTemplate = 'Email Template', 
    SFDC_Field = 'Field', 
    SFDC_FieldPermission = 'Field Permission', 
    SFDC_FieldSet = 'Field Set', 
    SFDC_Flow = 'Flow', 
    SFDC_FlowVersion = 'Flow Version', 
    SFDC_Group = 'Group', 
    SFDC_HomePageComponent = 'Home Page', 
    SFDC_KnowledgeArticle = 'Article', 
    SFDC_LightningAuraComponent = 'Aura Component', 
    SFDC_LightningPage = 'Page', 
    SFDC_LightningWebComponent = 'Lightning Web Component', 
    SFDC_Limit = 'Limit', 
    SFDC_Object = 'Object', 
    SFDC_ObjectPermission = 'CRUD', 
    SFDC_ObjectRelationShip = 'Relationship', 
    SFDC_ObjectType = 'Object Type', 
    SFDC_Organization = 'Organization', 
    SFDC_Package = 'Package', 
    SFDC_PageLayout = 'Page Layout', 
    SFDC_PermissionSet = 'Permission Set', 
    SFDC_PermissionSetLicense = 'Permission Set License', 
    SFDC_Profile = 'Profile', 
    SFDC_ProfilePasswordPolicy = 'Password Policy', 
    SFDC_ProfileRestrictions = 'Profile Restrictions', 
    SFDC_ProfileIpRangeRestriction = 'Profile Ip Range Restrictions', 
    SFDC_ProfileLoginHourRestriction = 'Profile Login Hour Restrictions', 
    SFDC_RecordType = 'Record Type', 
    SFDC_Report = 'Report', 
    SFDC_StaticResource = 'Sstatic Resource', 
    SFDC_User = 'User', 
    SFDC_UserRole = 'Role', 
    SFDC_ValidationRule = 'Validation Rule', 
    SFDC_VisualForceComponent = 'Visualforce Component', 
    SFDC_VisualForcePage = 'Visualforce Page', 
    SFDC_WebLink = 'Web Link', 
    SFDC_Workflow = 'Workflow'
}