/**
 * @description Recipe aliases
 */
export enum RecipeAliases {
    APEX_CLASSES = 'apex-classes',
    APEX_TESTS = 'apex-tests',
    APEX_TRIGGERS = 'apex-triggers',
    APEX_UNCOMPILED = 'apex-uncompiled',
    APP_PERMISSIONS = 'app-permissions',
    BROWSERS = 'browsers',
    COLLABORATION_GROUPS = 'collaboration-groups',
    CURRENT_USER_PERMISSIONS = 'current-user-permissions',
    CUSTOM_FIELDS = 'custom-fields',
    CUSTOM_LABELS = 'custom-labels',
    CUSTOM_TABS = 'custom-tabs',
    DASHBOARDS = 'dashboards',
    DOCUMENTS = 'documents',
    EMAIL_TEMPLATES = 'email-templates',
    FIELD_PERMISSIONS = 'field-permissions',
    FLOWS = 'flows',
    GLOBAL_VIEW = 'global-view',
    HARDCODED_URLS_VIEW = 'hardcoded-urls',
    HOME_PAGE_COMPONENTS = 'home-page-components',
    INTERNAL_ACTIVE_USERS = 'internal-active-users',
    KNOWLEDGE_ARTICLES = 'knowledge-articles',
    LIGHTNING_AURA_COMPONENTS = 'lightning-aura-components',
    LIGHTNING_PAGES = 'lightning-pages',
    LIGHTNING_WEB_COMPONENTS = 'lightning-web-components',
    OBJECT = 'object',
    OBJECT_PERMISSIONS = 'object-permissions',
    OBJECTS = 'objects',
    OBJECT_TYPES = 'object-types',
    ORGANIZATION = 'org-information',
    PACKAGES = 'packages',
    PAGE_LAYOUTS = 'page-layouts',
    PERMISSION_SETS = 'permission-sets',
    PERMISSION_SET_LICENSES = 'permission-set-licenses',
    PROCESS_BUILDERS = 'process-builders',
    PROFILE_PWD_POLICIES = 'profile-password-policies',
    PROFILE_RESTRICTIONS = 'profile-restrictions',
    PROFILES = 'profiles',
    PUBLIC_GROUPS = 'public-groups',
    QUEUES = 'queues',
    RECORD_TYPES = 'record-types',
    REPORTS = 'reports',
    STATIC_RESOURCES = 'static-resources',
    USER_ROLES = 'user-roles',
    VALIDATION_RULES = 'validation-rules',
    VISUALFORCE_COMPONENTS = 'visualforce-components',
    VISUALFORCE_PAGES = 'visualforce-pages',
    WEBLINKS = 'web-links',
    WORKFLOWS = 'workflows'
}